In [2]:
import pandas as pd
import os

In [13]:
os.listdir()

['medianas_vr.png',
 'panoramica2_vr.png',
 '.DS_Store',
 'rnped_fuerocomun',
 'promedio_hombre.png',
 'promedios_vr.png',
 'pi-face-recognition',
 'mediana_mujer1.png',
 'mediana_mujer.png',
 'panoramica.png',
 'ReadMe.md',
 'panoramica_vr.png',
 'personasdesaparecidas.json',
 'mediana_hombre.png',
 'Imagenes',
 'promedio_mujer.png',
 'Procesamiento de caras desaparecidas.ipynb',
 '.ipynb_checkpoints',
 '.git',
 'imagen_promedio.png',
 'procesamiento de datos desaparecidos.ipynb',
 'mediana_hombre1.png']

In [14]:
os.listdir('rnped_fuerocomun')

['.DS_Store',
 'rnped_fuerocomun_31_07_17_2.csv',
 'rnped_fuerocomun_01_12_2017_2.csv',
 'report_12_01_2018_2.csv']

In [15]:
df1=pd.read_csv('rnped_fuerocomun/rnped_fuerocomun_31_07_17_2.csv')
df2=pd.read_csv('rnped_fuerocomun/rnped_fuerocomun_01_12_2017_2.csv')
df3=pd.read_csv('rnped_fuerocomun/report_12_01_2018_2.csv')
print(df1.shape,df2.shape,df3.shape)

(32277, 21) (33513, 21) (34441, 22)

In [11]:
pd.get_dummies(df1['identificado'])

       completo  incompleto  no
0             1           0   0
1             1           0   0
2             1           0   0
3             1           0   0
4             1           0   0
5             1           0   0
6             1           0   0
7             1           0   0
8             1           0   0
9             1           0   0
10            1           0   0
11            1           0   0
12            1           0   0
13            1           0   0
14            1           0   0
15            1           0   0
16            1           0   0
17            1           0   0
18            1           0   0
19            1           0   0
20            1           0   0
21            1           0   0
22            1           0   0
23            1           0   0
24            1           0   0
25            1           0   0
26            1           0   0
27            1           0   0
28            1           0   0
29            1           0   0
...         ...         ...  ..
32247         0           0   1
32248         0           0   1
32249         0           0   1
32250         0           0   1
32251         0           0   1
32252         0           0   1
32253         0           0   1
32254         0           0   1
32255         0           0   1
32256         0           0   1
32257         0           0   1
32258         0           0   1
32259         0           0   1
32260         0           0   1
32261         0           0   1
32262         0           0   1
32263         0           0   1
32264         0           0   1
32265         0           0   1
32266         0           0   1
32267         0           0   1
32268         0           0   1
32269         0           0   1
32270         0           0   1
32271         0           0   1
32272         0           0   1
32273         0           0   1
32274         0           0   1
32275         0           0   1
32276         0           0   1

[32277 rows x 3 columns]

In [8]:
df2.head()

,index,prim_nombre,seg_nombre,apellido_pat,apellido_mat,fuerocomun_complexion,fuerocomun_dependencia,fuerocomun_desapentidad,fuerocomun_desapfecha,fuerocomun_desaphora,...,fuerocomun_desapmunicipio,fuerocomun_desappais,fuerocomun_descripcion,fuerocomun_discapacidad,fuerocomun_edad,fuerocomun_estatura,fuerocomun_etnia,fuerocomun_nacionalidad,fuerocomun_sexo,identificado
0,201,DANIEL,NaN,ISLAS,CAZARES,Delgada,FGE - SONORA,SONORA,01/01/2016,02:00:00,...,CAJEME,MEXICO,NO ESPECIFICADO,NO ESPECIFICADO,27,1.6,NO ESPECIFICADO,MEXICANA,HOMBRE,completo
1,8026,EMMA,NaN,OCHOA,SOLAR,Mediana,FGE - PUEBLA,PUEBLA,07/11/2016,09:00:00,...,PUEBLA,MEXICO,NO ESPECIFICADO,NO ESPECIFICADO,33,1.57,NO ESPECIFICADO,MEXICANA,MUJER,completo
2,8027,ADOLFO,NaN,VARGAS,ZAPOTECO,Robusta,FGE - GUERRERO,GUERRERO,07/11/2016,01:30:00,...,CHILAPA DE ALVAREZ,MEXICO,DOS PERFORACIONES EN LA OREJA DERECHA Y UNA EN...,NO ESPECIFICADO,25,1.7,NO ESPECIFICADO,MEXICANA,HOMBRE,completo
3,8028,MARGARITA,NaN,JARAMILLO,SANCHEZ,NO ESPECIFICADO,PGJ - NUEVO LEON,NUEVO LEON,07/11/2016,03:59:00,...,GRAL. ESCOBEDO,MEXICO,NO ESPECIFICADO,NO ESPECIFICADO,36,NO ESPECIFICADO,NO ESPECIFICADO,MEXICANA,MUJER,completo
4,8029,DULCE MARIA,NaN,CASTILLO,BUENDIA,Delgada,FGJ - ESTADO DE MEXICO,ESTADO DE MEXICO,07/11/2016,12:50:00,...,CHICOLOAPAN,MEXICO,NO ESPECIFICADO,NO ESPECIFICADO,15,1.6,NO ESPECIFICADO,MEXICANA,MUJER,completo

In [9]:
df3.head()

,prim_nombre,seg_nombre,apellido_pat,apellido_mat,fuerocomun_complexion,fuerocomun_dependencia,fuerocomun_desapentidad,fuerocomun_desapfecha,fuerocomun_desaphora,fuerocomun_desaplocalidad,...,fuerocomun_descripcion,fuerocomun_discapacidad,fuerocomun_edad,fuerocomun_estatura,fuerocomun_etnia,fuerocomun_nacionalidad,fuerocomun_sexo,status,identificado,duplicado
0,ALONSO,NaN,JIRON,MENDEZ,NO ESPECIFICADO,FGE - QUERETARO,QUERETARO,01/01/1971,12:00:00,SAN JUAN DEL RIO,...,NO ESPECIFICADO,NO ESPECIFICADO,50,NO ESPECIFICADO,NO ESPECIFICADO,MEXICANA,HOMBRE,update,completo,0
1,JESUS ANTONIO,NaN,RAMIREZ,FRAIRE,Delgada,FGE - CHIHUAHUA,CHIHUAHUA,01/01/1979,12:00:00,JUAREZ,...,NO ESPECIFICADO,NO ESPECIFICADO,68,1.65,NO ESPECIFICADO,MEXICANA,HOMBRE,update,completo,0
2,FERNANDO,NaN,DE LA PENA,VITAL,Mediana,FGE - CHIHUAHUA,CHIHUAHUA,01/01/1997,12:00:00,JUAREZ,...,ABDOMEN,NO ESPECIFICADO,66,1.75,NO ESPECIFICADO,MEXICANA,HOMBRE,update,completo,0
3,JESUS,NaN,SANDOVAL,ORTIZ,Mediana,FGE - DURANGO,DURANGO,01/01/1997,12:00:00,DURANGO,...,NO ESPECIFICADO,NO ESPECIFICADO,73,1.7,NO ESPECIFICADO,MEXICANA,HOMBRE,update,completo,0
4,FEDERICO,NaN,LUJAN,DIAZ,Robusta,FGE - CHIHUAHUA,CHIHUAHUA,01/01/1997,12:00:00,SAUCILLO,...,CICATRIZ DE BALA EN CRANEO,NO ESPECIFICADO,55,1.6,NO ESPECIFICADO,MEXICANA,HOMBRE,update,completo,0